### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by jasonrogena** [ilri/odktools#1]
It might be better to move this project from ilri/odktools to ilri/rmg-odktools. Most projects in the organisation are now following this naming convention.

**Comment by oguya** [comment]
Good idea @jasonrogena. I think the convention is to prefix your project name with your department's name/initials - `$DEPT-$PROJECTNAME` - for example: `rmg-ansible-public`

**Comment by oguya** [comment]
This issue also applies to [ilri/meta](https://github.com/ilri/meta) repo.

**Comment by qlands** [comment]
No need for this.
