### ISSUE TITLE
error: private/qzipwriter_p.h: No such file or directory

### ISSUE THREAD

**Issue by collinsod** [ilri/odktools#2]
There seems to be a library missing in this: I get this error when I try to build. 

/home/cadoyo/Data/Tools/odktools/3rdparty/QtXlsxWriter/src/xlsx/xlsxzipwriter.cpp:27: error: private/qzipwriter_p.h: No such file or directory
 #include <private/qzipwriter_p.h>
                                  ^

Collins

**Comment by qlands** [comment]
ODKToMySQL requires QT 5.X. Try to build it with QT 5 and check if the error persists.

**Comment by qlands** [comment]
You need to QT Internals for building it.
