### ISSUE TITLE
Check for duplicated options

### ISSUE THREAD

**Issue by qlands** [ilri/odktools#44]
Currently, ODK to MySQL generate insert scripts from ODK options but it is only when such scripts are executed that one is able to determine if an option has repeated codes. The tool should check for those errors and report about them.

**Comment by qlands** [comment]
Fixed in 6f78259

**Comment by essymanyeki16** [comment]
Hi Carlos,Happy new year.
Thanks for all the updates. My server crushed, I hope as I redo the
installation bow it's will be well, without that error. Thanks.

God bless, enjoy your evening.


On Jan 13, 2018 7:12 PM, Carlos Quiros <notifications@github.com>
wrote:Currently, ODK to MySQL generate insert scripts from ODK options
but it is only when such scripts are executed that one is able to
determine if an option has repeated codes. The tool should check for
those errors and report about them.
