### ISSUE TITLE
Error: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by collinsod** [ilri/odktools#6]
There seems to be a bug with this new odk tool. When I try to run ODKToMYSQL as shown below:
cadoyo@ILRI16648:~/Data/Projects/GHGENandi$ ~/Data/Tools/odktools/ODKToMySQL/odktomysql -v q6seca_hhid -t geninfo -x ~/Data/Projects/GHGENandi/Nandi_FinHH/XLS050_JO.xlsx

Well I know, its a memory problem but I cant just seem to find where the bug is.

Collins

**Comment by qlands** [comment]
Hi,

This happens when the odktomysql runs using QT 4.X libraries. If your Linux has both QT4 and QT5 then you need to change the environment to QT5. This can be done in a terminal with:

```sh
QT5DIR=/path/to/QT5
QTDIR=/path/to/QT5

export QTDIR
export QT5DIR

CPLUS_INCLUDE_PATH=$QT5DIR/include
export CPLUS_INCLUDE_PATH

PATH="$QT5DIR/bin:$PATH"
export PATH

LD_LIBRARY_PATH="$QT5DIR/lib:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH
```
