### ISSUE TITLE
processing ODK data with multiple select

### ISSUE THREAD

**Issue by hnjamba** [ilri/odktools#9]
There is an issue while processing data with a multi-select column where the related field in the multi-select table does not get added in the create.sql file. Everything works fine until you get to the processing of the JSON into mysql where yo get the error about the missing field in a table.

Attached are the xlsx, separation file xml and a few JSON files for the testing. 

NOTE: Github refused to upload .zip file so I renamed the attached file to .png Download it and rename to .zip to be able to open the files

![testfiles](https://cloud.githubusercontent.com/assets/12273427/11554476/5ab417b4-99a9-11e5-8191-16dbc874da01.png)

**Comment by qlands** [comment]
Fixed in dfd8e2b
